title: ETHERBLACK INDUSTRIES
description: MASONS OF FORM AND THOUGHT

# url: http://etherblk.com
# baseurl: "/frameset"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation--left:
  - title: About
    url: /about
  - title: Services
    url: /services
  # - title: Feed
  #   url: /feed

navigation--right:
  # - title: Work
  #   url: /work
  - title: Store
    url: https://etherblack.bigcartel.com/

collections:
  specimen:
    output: true
    permalink: /specimen/:path/

social:
  - icon: icon-facebook
    url: https://facebook.com/etherblack
    alt: EtherBlk on Facebook
  - icon: icon-twitter
    url: https://twitter.com/etherblk
    alt: EtherBlk on Twitter
  - icon: icon-instagram
    url: https://instagram.com/etherblk
    alt: EtherBlk on Instagram

google_analytics: "UA-58263416-1"
